package com.kenss.utilities;

public final class Constants {
	
	//Processor descriptions & their codes
	public static final String CORE2DUO = "Core2Duo";
	public static final String CORE2DUOCODE = "C2D";
	public static final String COREDUO = "CoreDuo";
	public static final String COREDUOCODE = "CD";	
	public static final String DUALCOREI3 = "DualCorei3";
	public static final String DUALCOREI3CODE = "DCi3";
	public static final String DUALCOREI5 = "DualCorei5";
	public static final String DUALCOREI5CODE = "DCi5";
	public static final String DUALCOREI7 = "DualCorei7";
	public static final String DUALCOREI7CODE = "DCi7";
	public static final String C2EXTREME = "C2Extreme";
	public static final String C2EXTREMECODE = "C2 Extreme";
	public static final String QUADCOREI3 = "QuadCorei3";
	public static final String QUADCOREI3CODE = "QCi3";
	public static final String QUADCOREI5 = "QuadCorei5";
	public static final String QUADCOREI5CODE = "QCi5";
	public static final String QUADCOREI7 = "QuadCorei7";
	public static final String QUADCOREI7CODE = "QCi7";
	public static final String A4CHIP = "A4 Chip";
	public static final String A4CHIPCODE = "A4";
	public static final String A5CHIP = "A5 Chip";
	public static final String A5CHIPCODE = "A5";
	public static final String A6CHIP = "A6 Chip";
	public static final String A6CHIPCODE = "A6";
	public static final String A7CHIP = "A7 Chip";
	public static final String A7CHIPCODE = "A7";
	public static final String A8CHIP = "A8 Chip";
	public static final String A8CHIPCODE = "A8";
	public static final String A9CHIP = "A9 Chip";
	public static final String A9CHIPCODE = "A9";
	public static final String A5XCHIP = "A5X Chip";
	public static final String A5XCHIPCODE = "A5X";
	public static final String A6XCHIP = "A6X Chip";
	public static final String A6XCHIPCODE = "A6X";
	public static final String A7XCHIP = "A7X Chip";
	public static final String A7XCHIPCODE = "A7X";
	public static final String A8XCHIP = "A8X Chip";
	public static final String A8XCHIPCODE = "A8X";
	public static final String A9XCHIP = "A9X Chip";
	public static final String A9XCHIPCODE = "A9X";
	public static final String QUADXEON6CORE = "Quad XEON6Core";
	public static final String QUADXEON6CORECODE = "XEON 6 Core";
	public static final String DUALCOREM = "DualCoreM";
	public static final String DUALCOREMCODE = "DCM";
	public static final String QUADCOREM = "QuadCoreM";
	public static final String QUADCOREMCODE = "QCM";
	public static final String POWERPC970FX = "PowerPC 970fx";
	public static final String POWERPC970FXCODE = "G5";
	public static final String S1CHIP = "S1";
	public static final String S1CHIPCODE = "S1";
	public static final String S1PCHIP = "S1P";
	public static final String S1PCHIPCODE = "S1P";
	public static final String QUADCOREIXEON = "QuadCoreiXeon";
	public static final String QUADCOREIXEONCODE = "QCiX";
	public static final String XEON8CORE = "Xeon8Core";
	public static final String XEON8CORECODE = "X8C";
	public static final int BARCODE_WIDTH = 80;
	public static final int BARCODE_HEIGHT = 40;
	public static String DEFAULT_FILE_PATH = "/Users/pguttikonda/Desktop/MacWarehouse/generated/";
	public static String MASTER_PRODUCT_FILE_NAME;
	public static boolean DOWNLOAD_FROM_GDRIVE;
	public static String GDRIVE_USER_INFO;
	public static String GDRIVE_CREDS_FILE;
	public static String GENERATED_FILE_PATH;
	public static String PRINTER_NAME;
	public static String LABEL_TEMPLATE;
}
